### ISSUE TITLE
Input - Label is stuck when I have onChange and value attributes 

### ISSUE THREAD

**Issue by onurmhb** [Evo-Forge/Essence#50]
` <Input onChange={this._handleSearch.bind(this)} value={this.props.term} type={'text'} name={'label'} label={'Search for an article'}/>`

If i remove the onChange and value the label floats normally.

**Comment by hetmann** [comment]
Thanks @onurmhb for the bug, I will check it out, do some work and update the npm module, I think today I will update it. Let us know what issues you have or what improvements you need.

**Comment by hetmann** [comment]
@onurmhb the `essence-input` component was updated at version 1.0.7 so you can use the module with **npm i essence-input**

Let me know what bugs you find so I can fix them.

Thanks again for you feedback, we appreciate you help :)

**Comment by hetmann** [comment]
Thanks again @onurmhb  - component was updated at version 1.0.9 the counter has the default value to `false` so only when the counter is set to an integer value will be displayed, the event target is passed to the onChange callback.
