### ISSUE TITLE
Switches not keyboard navigable (usability/accessibility)

### ISSUE THREAD

**Issue by patrick-jones** [Evo-Forge/Essence#60]
Native radio buttons, checkboxes etc. can be navigated using the tab key, and (de)selected using either the space key or arrow keys.  Essence does not allow this.

I played around with chrome dev tools on [the example switches page](http://getessence.io/react-component/switches) and I was able to restore functionality by removing `display: none` from `.e-radio input[type=radio]` and `.e-switches label input[type=checkbox]`. I used `opacity: 0` and `position: absolute` to visibly remove them.

This actually worked quite nicely, except that there was no visual indication of the moving focus.  A real fix would need to add the little outline to the visible part of the component to be effective. But this seems like a promising approach.

**Comment by hetmann** [comment]
@patrick-jones I updated the `essence-switch` component. Give it a try by installing the latest version `npm i essence-switch`

**Comment by patrick-jones** [comment]
Wow, that was quick.  I didn't even get the chance to clone the project.

**Comment by hetmann** [comment]
@patrick-jones 3 days I can say are a lot :) anyway let me know what you think about the framework.
