### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by jamesdbruner** [Evo-Forge/Essence#72]
Looks like your website [getessence.io](http://getessence.io/) is having some issues.   All I'm able to see is a white page with the text

> getessence.io
2017 Copyright. All Rights Reserved. 
The Sponsored Listings displayed above are served automatically by a third party. Neither the service provider nor the domain owner maintain any relationship with the advertisers. In case of trademark issues please contact the domain owner directly (contact information can be found in whois). 
Privacy Policy

**Comment by hetmann** [comment]
Hi @jamesdbruner the project is discontinued by the company and didn't extended the domain. Contact me by email for any support.

**Comment by jamesdbruner** [comment]
Thanks for letting me know!
